# Conclusion

We have obtained a broad view on the NBA's data, and perfermed several analysis. In this final project, our focus is on data of NBA regular season and playoffs in season 2021-2022. The major goal for our project is determining the relationship between the factors, and tried to explore which of them are keys factors for a team to win.
In regular season, we have analyzed each team’s performance base on conference. Performance includes: field goals made(FGM), 3 point field goals made(3PM), free throws made(FTM), assists(AST), offensive rebounds(OREB), defensive rebounds(DREB), blocks(BLK) and steals(STL). Among these features, FGM, 3PM, FTM, AST and OREB are categorized to be offensive statistics since they are related to a team’s offensive performance. DREB, BLK and STL are considered as defensive statistics since they reveal the defense level of a team. In playoffs, we did similar analyze like regular season. Then we discussed why those teams perform better than those that can not enter the playoffs.
As from the result sections, we obtained several conclustions from the analysis:
1. We found that strong teams (who enter playoff) have both the high 3 point goals made and 3 point goals percentage. Top ranked teams among weak teams (do not enter playoff) have both low 3 point goals made and 3 point goals percentage. However, those last few teams have a very high 3 point goals made but lowest 3 point goals percentage. It can be explained by the level gap. Strong teams are always strong, they can make 3 point easier and offensive efficiently. Top ranked teams among weak teams may have good offensive abilities, but they lack the 3 points goals to open up the gap in order to win, that’s why they lose.
2. For the general field goals performance. This is the most critical factor that reflects a team’s performance because most of the time, a team win points through general field goals. In playoff, although the trend is very weak, field goals made drops slightly as rank drops while in field goals percentage, they are quite similar. That means each team’s shooting percentage is similar, all of them can shoot very good. However, stronger teams have more opportunities to shoot because of their stronger offensive abilities. That’s why they can win. And we can conclude that although each team in playoff is strong, they still have subtle level gap. In regular season this trend becomes very notable. Strong teams always have higher field goals made and field goals percentage while weak teams have lower. They have a very clear level gap.
3. For the effect of Free throws, Intuitively thinking, Free throws serve as a supporting factor for winning, not the key factor, since Free Throws only worth one point each, and the accuracy depends on the player heavily. We should not expect more Free Throws resulting in higher rank. As expected, in Playoff the Free Throws made does not lead to a higher ranking. In fact, the team in the first place even has a low amount of Free Throws made. This happened again in the analysis in Regular Season, in Regular Season the Free Throws made also does not lead to a higher ranking. In fact, the team in the first place even has a low amount of Free Throws made in general.
4. For the effect of Rebounds, Intuitively thinking, Rebounds made serve as a key factor for winning, since each rebound means the opportunity for a team to be ofensive, and have the change to score points. We should expect more rebounds being made resulting in higher rank. As expected, in Playoff the Rebounds made does lead to a higher ranking. In fact, the team in the first place even has a high amount of rebounds made. This happened again in the analysis in Regular Season more obviously, in Regular Season the rebounds made also leads to a higher ranking. In fact, the team in the first place even has a how amount of rebounds made in general.
5. For the effect of Personal Fouls, Intuitively thinking, Personal Fouls should have a negative correlation with ranking, since Personal Fouls will provide more attacking chance for the opposite team, and the player might have to retreat. We should expect less Personal Fouls in higher rank. As expected, in Playoff less Personal Fouls does lead to a higher ranking. In fact, the team in the first place even has a low amount of Personal Fouls. This does not happened again in the analysis in Regular Season, in Regular Season less Personal Fouls does not lead to a higher ranking from the plot. One of the reasons could be the skill differences are to large between teams. Personal Fouls factor is not strong enough to secure a high rank, although more attacking opportunities were provided.

All the above conclusion seems to be reasonable for determining the path for the competition of each team, in the basketball perspective:
